from .field_types import (
    BooleanFieldType,
    CharFieldType,
    ChoiceFieldType,
    DateFieldType,
    DateTimeFieldType,
    DecimalFieldType,
    DictFieldType,
    DurationFieldType,
    EmailFieldType,
    FileFieldType,
    FilePathFieldType,
    FloatFieldType,
    HiddenFieldType,
    HStoreFieldType,
    ImageFieldType,
    IntegerFieldType,
    IPAddressFieldType,
    JSONFieldType,
    ListFieldType,
    ModelFieldType,
    MultipleChoiceFieldType,
    NullBooleanFieldType,
    PrimaryKeyRelatedFieldType,
    ReadOnlyFieldType,
    RegexFieldType,
    SerializerMethodFieldType,
    SlugFieldType,
    TimeFieldType,
    URLFieldType,
    UUIDFieldType,
)


FIELD_TYPES = {
    'BooleanField': BooleanFieldType,
    'CharField': CharFieldType,
    'ChoiceField': ChoiceFieldType,
    'DateField': DateFieldType,
    'DateTimeField': DateTimeFieldType,
    'DecimalField': DecimalFieldType,
    'DictField': DictFieldType,
    'DurationField': DurationFieldType,
    'EmailField': EmailFieldType,
    'FileField': FileFieldType,
    'FilePathField': FilePathFieldType,
    'FloatField': FloatFieldType,
    'HiddenField': HiddenFieldType,
    'HStoreField': HStoreFieldType,
    'ImageField': ImageFieldType,
    'IntegerField': IntegerFieldType,
    'IPAddressField': IPAddressFieldType,
    'JSONField': JSONFieldType,
    'ListField': ListFieldType,
    'ModelField': ModelFieldType,
    'MultipleChoiceField': MultipleChoiceFieldType,
    'NullBooleanField': NullBooleanFieldType,
    'PrimaryKeyRelatedField': PrimaryKeyRelatedFieldType,
    'ReadOnlyField': ReadOnlyFieldType,
    'RegexField': RegexFieldType,
    'SerializerMethodField': SerializerMethodFieldType,
    'SlugField': SlugFieldType,
    'TimeField': TimeFieldType,
    'URLField': URLFieldType,
    'UUIDField': UUIDFieldType,
}